mkit:
  my_network:
    ip: 10.210.198.1
  haproxy:
    config_dir: /etc/haproxy/haproxy.d
    ctrl:
      start:   /etc/init.d/haproxy start
      stop:    /etc/init.d/haproxy stop
      reload:  /etc/init.d/haproxy restart
      restart: /etc/init.d/haproxy restart
      status:  /etc/init.d/haproxy status
      bin: /usr/sbin/haproxy
  database:
    env: development

